general:
  - name: IP設定
    command: gedit -s ~/catkin_ws/set_ip.sh; source ~/.bashrc
  - name: roscore
    command: roscore
  - name: rqt_graph
    command: rqt_graph
  - name: rqt
    command: rqt
  - name: param設定GUI
    command: rosrun ros_utils param_setting_gui.py 

settings:
  - name: bashrc編集
    command: gedit -s ~/.bashrc; source ~/.bashrc
  - name: gitconfig編集
    command: gedit -s ~/.gitconfig
  - name: aptconf編集
    command: sudo gedit -s /etc/apt/apt.conf
  - name: condarc編集
    command: gedit -s ~/.condarc   
  - name: 時刻合わせ
    command: sudo date -s "$( wget -q http://worldtimeapi.org/api/timezone/Asia/Tokyo -O - | grep -oE \"datetime\":\"[^\"]* | sed s/\"datetime\":\"// )"
    
vision: 
  - name: Realsense起動
    command: roslaunch realsense2_camera rs_rgbd.launch 
    option: "align_depth:=True"
  - name: CNN+SVM物体認識
    command: rosrun ros_vision tabletop_object_recognition.py 
  - name: 画像保存
    command: rosrun ros_vision image_saver.py
  - name: SSD物体認識
    command: rosrun ros_vision ssd_object_recognition.py
  - name: ARマーカー認識
    command: rosrun ros_vision ar_marker_recognition.py
  - name: OpenPose
    command: rosrun ros_vision open_pose.py
    
speech:
  - name: Google音声認識
    command: roslaunch ros_google_speech google_speech.launch
    option: 

CRANE X7:
  - name: CRANE X7起動
    command: sudo chmod 666 /dev/ttyUSB0; roslaunch crane_x7_bringup demo.launch
    option: "fake_execution:=false"
  - name: トルクOn
    command: rosrun ros_manipulation cranex7_enable_torque.py 1
  - name: トルクOff
    command: rosrun ros_manipulation cranex7_enable_torque.py 0
  - name: キャリブレーション実行
    command: rosrun ros_manipulation camera_calibration.py
    option: 0.0 0.0

Turtlebot2(kobuki):
  - name: 地図生成
    command: roslaunch ros_navigation kobuki_slam.launch
    option: ""
  - name: 地図保存
    command: rosrun map_server map_saver
    option: -f ~/map
  - name: 地図表示
    command: rosrun ros_navigation map_viewer.py
    option: ~/map.yaml
  - name: ナビゲーション
    command: roslaunch ros_navigation kobuki_navigation.launch
    option: "map_file:=$HOME/map.yaml"
  - name: キーボード入力
    command: roslaunch ros_navigation kobuki_teleop_key.launch
    option: ""

Turtlebot3:
  - name: 地図生成
    command: roslaunch turtlebot3_slam turtlebot3_slam.launch
    option: ""
  - name: 地図保存
    command: rosrun map_server map_saver
    option: -f ~/map
  - name: 地図表示
    command: rosrun ros_navigation map_viewer.py
    option: ~/map.yaml
  - name: ナビゲーション
    command: roslaunch turtlebot3_navigation turtlebot3_navigation.launch
    option: "map_file:=$HOME/map.yaml"
  - name: キーボード入力
    command: roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch
    option: ""

Sciurus17:
  - name: Sciurus17起動
    command: roslaunch sciurus17_bringup sciurus17_bringup.launch

Stretch:
  - name: Strechキャリブレーション
    command: ~/catkin_ws/src/ros_stretch/scripts/run_stretch_calibration.sh
    option: ""
  - name: Strech driver起動
    command: ~/catkin_ws/src/ros_stretch/scripts/run_stretch_driver.sh
    option: ""
  - name: xboxコントローラ復帰
    command: /usr/bin/hello_robot_xbox_teleop.sh 
    option: ""
  - name: SLAM起動
    command: roslaunch stretch_navigation mapping.launch
    option: ""
  - name: 地図保存
    command: rosrun map_server map_saver
    option: "-f $HOME/test"
  - name: Navigation起動
    command: roslaunch stretch_navigation navigation.launch 
    option: "map_yaml:=$HOME/test5.yaml"
  - name: 地図表示
    command: rosrun ros_navigation map_viewer.py 
    option: "~/test.yaml"
  - name: Realsense起動
    command: roslaunch realsense2_camera rs_rgbd.launch 
    option: "align_depth:=True"
  - name: Strecth用ARマーカー認識
    command: roslaunch ros_stretch stretch_ar_marker_recognition.launch
    option: ""
  - name: Strecth用机上物体認識
    command: roslaunch ros_stretch stretch_tabletop_object_recognition.launch
    option: "svm_model:=$HOME/svm_data_1015.sav"
  - name: StrecthコントロールGUI
    command: rosrun ros_stretch stretch_controller_gui.py
    option: ""
  - name: バッテリーチェック
    command: ~/catkin_ws/src/ros_stretch/scripts/run_battery_check.sh 
    option: ""
